language: python
before_install:
- sudo apt-get update -q
- sudo apt-get install libpulse-dev swig -y
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install textract
script:
- ls -lR
- python generate_resume_template.py
- python check_wordfile.py
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "t-v"
  - git config --local user.email "timothy.vandenbrande@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  name: Curiculum Vitae
  body: My from YAML generated resume.
  provider: releases
  api_key:
    secure: U0zoMtGM1XGSkPWYueJoy5T51nNbF/8odyYdsJNdOBEu8gzmsYLDcA2jkC+jzYMkW7RSRl5PQrl+J18yH1zUHhxGSToqP2sCbQOVBU2r9PMhg10OY+jVAoiRJtSGvYXo/pX+Ry+mXk6tcgdV/9Q2+NuGG3F/+4wiu+1V3W0Jr4A64aCD3KepL7aQacXkGVdc4iQ7NG5oXpFCgZ6gQZwK84KCyWcGwHBUpgEayyOqKVJZgImvo/FdZ+hcJ2TldTCtcZ5Hu5lSb3mhYr0q0+mJjeb+iqwtYpcU4een+VCw3S1OzzhkSoDCTHKDAHJACN6aqBWFfPXmkltTTLhPMgzJlY3x3zo98pvm2n8XJ3ypnAy2rGmZqT2YKF3YJ/RQxx2IMl5u02DHenZqiYaSa7IvCu4KbXl1GAFYlIkgwMQ6+Tdan/kcljI3qMqW3kIsI+v5ovnB4znfvYW0eliHIeXlhIy8IKVPr/z4zv1lkeLm5SSgTUjFmV26Wz27gxlGrT8Ge6ihEwIkjcoudWB213R/xTwclH50UmEwBISZRUYgHIWVDHML+i8gI4I9PwfuhD9LB07gCwUuGh7Utu601uw8wC+Syu16ChmNLSgVnsJucTQ6jKKn083jU+tUbxIvNvF4agx1+kGs1nBapdutJenHQBq+c77u4C8pDZY/RW5WnCI=
  file:
  - output/resume.docx
  - output/resume.md
  skip_cleanup: true
  overwrite: true
