---
language: python
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libpulse-dev swig -y
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install textract
script:
  - ls -lR
  - python generate_resume_template.py
  - python check_wordfile.py
deploy:
  provider: releases
  api_key: "frFgPfUBoWp15S4P/0U6NuynkvINORZfpNwZ295xb0sj2pzfA7VomYrnZ7z6Lanz0MWLuyui1rhVu8i+2zlQP2wd541vhgsdN2gMYIgGZcHgYEwCgGoUBNBV2Cc/cqMpOOzNdbM6JpjiHgfh06+ivN6fQxvTo1dMPhGskM5ZNKlvFnU04duzFE/DFI9Ny/M5W8uzMEfl2wRGgYu2tPeGwhP3JD7n6JWjQC1wLlFu0jL0dEDXCYIA9zYyaGpJReEog+u4u9oDcHg5z6bbKtLl8MkFGhKwYOEMCvwpdzMBkBTbifaqjEptjlp0VtdAMg4dwV0LfVMnl66sAk81OGRzXdGzlfdkwtEPQUNRtbIfMPGvzGVR3Y67SRzU3joXJXZBQlFEPa/RVwlaacgh4zEUB2i8XfZBoai0KJYE1AAVm6tlWudTsVCAPN+nKPQQQ5ZUnGX0KXnOW7F4EgonWRenWPOjJs+9JEHu+szUK8exEGzmTo3VvryQwAQbvKva3ztEEtuy6+wp2596cCwG5wfC9B/ioMPyXh8IvKJeyZaJ1CVgADyxNAt1WgOZPfNul3MwCdVjAaDCpQXL1Z6lOevd52+LWvbeaZQZpxsDtpuNFPu/XWNETm53ogfbd+0TK+Ipy9H+JUa9aJ/ssSWqm2wv7MHz+plivzOv3l88QBHXnfw="
  file:
    - "output/resume.docx"
    - "output/resume.md"
  skip_cleanup: true
  overwrite: true
